service: talents
# Create an optimized package for our functions
package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables

custom: ${file(../../serverless.common.yml):custom}

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  tracing:
    apiGateway: true
    lambda: true

  environment:
    stage: ${self:custom.stage}
    tableName: candidates

functions:
  validate:
    handler: validate.main
    events:
      - sns:
          arn: !ImportValue ${self:custom.stage}-ExtTalentsTopicArn
          topicName: validation
